// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the Sync tab's form.
 */
export interface Settings {
    /**
     * http or https
     */
    "scheme": string;

    /**
     * IP or hostname
     */
    "host": string;
    "port": string;
    "token": string;
    "enabled": boolean;
    "intervalSec": number;
}

/**
 * SyncStatus is shown in the manager's Sync tab.
 */
export interface SyncStatus {
    "enabled": boolean;
    "syncing": boolean;

    /**
     * unix ms of last success
     */
    "lastSync": number;
    "lastError": string;

    /**
     * server has E2E set up
     */
    "e2eServer": boolean;

    /**
     * ...but this device has no valid key
     */
    "e2eLocked": boolean;

    /**
     * this device encrypts uploads
     */
    "e2eEnabled": boolean;
}
