// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService is the frontend's API for reading and editing notes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./pkg/store/models.js";

/**
 * Create adds a new note and opens its window.
 */
export function Create(): $CancellablePromise<store$0.Note> {
    return $Call.ByID(955216145);
}

/**
 * Delete removes a note everywhere (a tombstone is synced).
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3620747094, id);
}

export function Get(id: string): $CancellablePromise<store$0.Note> {
    return $Call.ByID(2869398643, id);
}

/**
 * Hide closes a note's window; it stays in the manager.
 */
export function Hide(id: string): $CancellablePromise<void> {
    return $Call.ByID(4208199321, id);
}

export function HideAll(): $CancellablePromise<void> {
    return $Call.ByID(1876581632);
}

export function List(): $CancellablePromise<store$0.Note[] | null> {
    return $Call.ByID(1156407021);
}

/**
 * OpenManager shows the note manager window.
 */
export function OpenManager(): $CancellablePromise<void> {
    return $Call.ByID(3654476708);
}

/**
 * SetAnchored locks or unlocks a note in place.
 */
export function SetAnchored(id: string, anchored: boolean): $CancellablePromise<store$0.Note> {
    return $Call.ByID(919398815, id, anchored);
}

export function SetColor(id: string, color: string): $CancellablePromise<store$0.Note> {
    return $Call.ByID(3523630678, id, color);
}

export function SetContent(id: string, content: string): $CancellablePromise<store$0.Note> {
    return $Call.ByID(2971092880, id, content);
}

/**
 * Show opens a note's window.
 */
export function Show(id: string): $CancellablePromise<void> {
    return $Call.ByID(2774946216, id);
}

export function ShowAll(): $CancellablePromise<void> {
    return $Call.ByID(1362895531);
}
