// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService exposes the sync engine to the frontend and keeps note
 * windows in step with incoming changes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pogosync$0 from "./pkg/pogosync/models.js";

/**
 * Loop runs until ctx is cancelled.
 */
export function Loop(): $CancellablePromise<void> {
    return $Call.ByID(2991629216);
}

/**
 * Nudge schedules a sync shortly after a local edit.
 */
export function Nudge(): $CancellablePromise<void> {
    return $Call.ByID(612298585);
}

/**
 * Status returns the current sync status.
 */
export function Status(): $CancellablePromise<pogosync$0.Status> {
    return $Call.ByID(3788943212);
}

/**
 * SyncNow runs a sync immediately and returns its error, if any.
 */
export function SyncNow(): $CancellablePromise<void> {
    return $Call.ByID(4106994651);
}
