// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService manages sync settings and end-to-end encryption.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisableE2E turns off end-to-end encryption for every device on the server
 * and re-uploads notes in plaintext.
 */
export function DisableE2E(): $CancellablePromise<void> {
    return $Call.ByID(3416704430);
}

/**
 * EnableE2E turns on end-to-end encryption with passphrase. If the server
 * already uses E2E the passphrase must match; otherwise E2E is set up on the
 * server and all notes are re-uploaded encrypted.
 */
export function EnableE2E(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(2757341415, passphrase);
}

export function Get(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(710695688);
}

/**
 * Save stores settings. Pointing at a different server resets the sync
 * cursor and queues every note for upload.
 */
export function Save($in: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2704157817, $in);
}

/**
 * TestConnection checks the given (unsaved) settings against the server.
 */
export function TestConnection($in: $models.Settings): $CancellablePromise<string> {
    return $Call.ByID(4262511440, $in);
}
