// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Note is a note plus its device-local window state.
 */
export interface Note {
    "id": string;
    "content": string;
    "color": string;
    "deleted": boolean;
    "createdAt": number;

    /**
     * unix ms of the last synced-field edit
     */
    "updatedAt": number;

    /**
     * Local only, never synced.
     */
    "x": number;
    "y": number;
    "w": number;
    "h": number;
    "anchored": boolean;
    "hidden": boolean;
}
